# Generated by Django 5.0 on 2023-12-26 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre de la Categoría')),
            ],
        ),
        migrations.CreateModel(
            name='webBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre de la Rama')),
                ('boolean', models.BooleanField(default=False, verbose_name='Curso hecho')),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del Proyecto')),
                ('description', models.TextField(verbose_name='Descripción del Proyecto')),
                ('date', models.DateField(verbose_name='Fecha de Inicio')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.categoriaproyecto', verbose_name='Categoría del Proyecto')),
            ],
        ),
        migrations.AddField(
            model_name='categoriaproyecto',
            name='webBranch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.webbranch'),
        ),
    ]
