# Generated by Django 5.0 on 2024-01-01 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la Categoría')),
            ],
        ),
        migrations.CreateModel(
            name='WebBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la Rama')),
                ('is_cursor', models.BooleanField(default=False, verbose_name='Es Cursor')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Proyecto')),
                ('description', models.TextField(verbose_name='Descripción del Proyecto')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.projectcategory', verbose_name='Categoría del Proyecto')),
            ],
        ),
        migrations.AddField(
            model_name='projectcategory',
            name='web_branches',
            field=models.ManyToManyField(blank=True, to='portfolio.webbranch', verbose_name='Ramas Web'),
        ),
    ]
