# Generated by Django 5.0 on 2024-01-01 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webbranch',
            name='is_cursor',
        ),
    ]
