# Generated by Django 5.0 on 2023-12-26 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoriaProyecto',
            new_name='Classification',
        ),
    ]
