# Generated by Django 5.0 on 2023-12-26 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_rename_categoriaproyecto_classification'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Proyecto',
            new_name='Project',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='categoria',
            new_name='classification',
        ),
    ]
