# Generated by Django 5.0 on 2023-12-26 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_rename_proyecto_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github',
            field=models.CharField(default=None, max_length=255, verbose_name='Dirección github'),
        ),
        migrations.AddField(
            model_name='project',
            name='server',
            field=models.CharField(default=None, max_length=255, verbose_name='Dirección servidor'),
        ),
    ]
