# Generated by Django 5.0 on 2024-01-02 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_remove_projectcategory_web_branches_delete_webbranch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='category',
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.ManyToManyField(blank=True, to='portfolio.projectcategory', verbose_name='Categorías del Proyecto'),
        ),
    ]
