# Generated by Django 5.0 on 2024-01-06 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_remove_project_category_project_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectCategory',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='category',
            new_name='categories',
        ),
    ]
