# Generated by Django 5.0 on 2024-01-06 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='titles',
            field=models.CharField(default='', max_length=100, verbose_name='Títulos de la persona'),
        ),
    ]
